apiVersion: v1
kind: Secret
metadata:
  name: bookstore-broker-secret
  namespace: bookstore-broker
  labels:
    run: bookstore-broker
type: Opaque
data:
  username: YWRtaW4=
  password: c3VwZXJzZWNyZXQ=